version: '3.8'
services:
  web:
    depends_on:
      - postgresdb
    ports:
      - 8001:8001
    env_file:
      - web/.env
    image: j30v/api_2024
    volumes: 
      - ./web/main:/app/main/

  api:
    depends_on:
      - postgresdb
    ports:
      - 8002:8002
    env_file:
      - web/.env
    image: j30v/django_2024
    volumes: 
      - ./api/main:/app/main/

  postgresdb:
    image: postgres 
    restart : always
    platform : linux/amd64
    env_file:
      - web/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: